services:
  accounts_service:
    build:
      context: ./AccountsService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./AccountsService/instance:/app/instance

  game_service:
    build:
      context: ./GameService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - accounts_service
    environment:
      - FLASK_ENV=development
    volumes:
      - ./GameService/instance:/app/instance

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - accounts_service
      - game_service
      - redis
    environment:
      - NODE_ENV=development
