version: "3.8"

services:
  accounts_service:
    build:
      context: ./AccountsService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./AccountsService/instance:/app/instance # Mount the entire instance directory

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
